# Generated by Django 5.2.13 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenciaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('archivo', models.FileField(upload_to='calidad/evidencias/%Y/%m/')),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evidencias_calidad',
            },
        ),
        migrations.CreateModel(
            name='IncidenciaCalidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_rechazada', models.DecimalField(decimal_places=2, max_digits=12)),
                ('motivo', models.TextField()),
                ('comentarios', models.TextField(blank=True)),
                ('accion_correctiva', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_seguimiento', 'En seguimiento'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('cerrado_en', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Incidencia de calidad',
                'verbose_name_plural': 'Incidencias de calidad',
                'db_table': 'incidencias_calidad',
            },
        ),
    ]
