# Generated by Django 5.2.13 on 2026-06-07 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calidad', '0001_initial'),
        ('logistica', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evidenciacalidad',
            name='subido_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenciacalidad',
            name='detalle_orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias', to='logistica.detallefactura'),
        ),
        migrations.AddField(
            model_name='incidenciacalidad',
            name='orden',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidencias_calidad', to='logistica.ordencompra'),
        ),
        migrations.AddField(
            model_name='incidenciacalidad',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_calidad', to='logistica.producto'),
        ),
        migrations.AddField(
            model_name='incidenciacalidad',
            name='registrado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_registradas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evidenciacalidad',
            name='incidencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidencias', to='calidad.incidenciacalidad'),
        ),
    ]
