# Generated by Django 5.2.13 on 2026-06-07 22:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calidad', '0002_initial'),
        ('logistica', '0005_detalleorden_laboratorio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incidenciacalidad',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='incidencias_calidad', to='logistica.producto'),
        ),
    ]
