# Generated by Django 5.2.13 on 2026-06-07 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ambiental', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='accioncorrectiva',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='acciones_correctivas', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenteambiental',
            name='accion_correctiva',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='incidentes_ambientales', to='ambiental.accioncorrectiva'),
        ),
        migrations.AddField(
            model_name='medicion',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='mediciones_ambientales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='incidenteambiental',
            name='medicion',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='incidente', to='ambiental.medicion'),
        ),
    ]
