# Generated by Django 5.2.13 on 2026-06-07 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordencompra',
            options={'ordering': ['-serie', '-numero']},
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='serie',
            field=models.CharField(default='2026', max_length=10),
        ),
        migrations.AlterField(
            model_name='ordencompra',
            name='numero',
            field=models.PositiveIntegerField(verbose_name='Número correlativo'),
        ),
        migrations.AlterUniqueTogether(
            name='ordencompra',
            unique_together={('serie', 'numero')},
        ),
    ]
