# Generated by Django 5.2.13 on 2026-06-07 22:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0003_alter_ordencompra_options_ordencompra_serie_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='detalleorden',
            options={'ordering': ['numero_item']},
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='descripcion',
            field=models.CharField(default='', max_length=500),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='numero_item',
            field=models.PositiveIntegerField(default=1, verbose_name='N° ítem'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='unidad_medida',
            field=models.CharField(default='UND', max_length=20),
        ),
        migrations.AlterField(
            model_name='detalleorden',
            name='producto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='detalles_orden', to='logistica.producto'),
        ),
        migrations.AlterUniqueTogether(
            name='detalleorden',
            unique_together={('orden', 'numero_item')},
        ),
    ]
