# Generated by Django 5.2.13 on 2026-06-07 22:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0004_alter_detalleorden_options_detalleorden_descripcion_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='comentarios_validacion',
            field=models.TextField(blank=True, verbose_name='Comentarios validación documental (FEAT 02)'),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='control_calidad_estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente control calidad'), ('conforme', 'Conforme — sin rechazos'), ('con_rechazos', 'Con productos rechazados')], default='pendiente', max_length=20),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='control_calidad_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_calidad_realizados', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='ordencompra',
            name='fecha_control_calidad',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='laboratorio',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
