# Generated by Django 5.2.13 on 2026-06-07 22:47

import django.db.models.deletion
from django.db import migrations, models

UNIDADES = [
    ('UND', 'Unidad', 'und'),
    ('CAJA', 'Caja', 'cja'),
    ('FRASCO', 'Frasco', 'frs'),
    ('AMP', 'Ampolla', 'amp'),
    ('TUBO', 'Tubo', 'tub'),
    ('KG', 'Kilogramo', 'kg'),
    ('LT', 'Litro', 'lt'),
    ('PAR', 'Par', 'par'),
    ('ROLLO', 'Rollo', 'rll'),
]


def seed_unidades_y_migrar_productos(apps, schema_editor):
    UnidadMedida = apps.get_model('logistica', 'UnidadMedida')
    Producto = apps.get_model('logistica', 'Producto')
    for codigo, nombre, simbolo in UNIDADES:
        UnidadMedida.objects.get_or_create(
            codigo=codigo, defaults={'nombre': nombre, 'simbolo': simbolo},
        )
    und = UnidadMedida.objects.get(codigo='UND')
    for producto in Producto.objects.all():
        codigo = getattr(producto, 'unidad_medida', None) or 'UND'
        unidad = UnidadMedida.objects.filter(codigo=codigo).first() or und
        producto.unidad_id = unidad.id
        producto.save(update_fields=['unidad_id'])


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0005_detalleorden_laboratorio_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'marcas',
            },
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('simbolo', models.CharField(blank=True, max_length=10)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Unidad de medida',
                'verbose_name_plural': 'Unidades de medida',
                'db_table': 'unidades_medida',
            },
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías de producto'},
        ),
        migrations.AddField(
            model_name='producto',
            name='tipo',
            field=models.CharField(choices=[('producto', 'Producto'), ('servicio', 'Servicio')], default='producto', max_length=20),
        ),
        migrations.AddField(
            model_name='producto',
            name='marca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='productos', to='logistica.marca'),
        ),
        migrations.AddField(
            model_name='producto',
            name='unidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='productos', to='logistica.unidadmedida'),
        ),
        migrations.RunPython(seed_unidades_y_migrar_productos, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='producto',
            name='unidad_medida',
        ),
    ]
