# Generated by Django 5.2.13 on 2026-06-08 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0007_subcategorias_vencimiento'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='igv_incluido',
            field=models.BooleanField(default=False, help_text='True si el precio unitario ya incluye IGV (18%).'),
        ),
    ]
