# Generated by Django 5.2.13 on 2026-06-08 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistica', '0008_detalle_igv_incluido'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='marca',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
