# Generated by Django 5.2.13 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('clasificacion', models.CharField(choices=[('informacion', 'Información'), ('software', 'Software'), ('hardware', 'Hardware'), ('personal', 'Personal'), ('servicios', 'Servicios'), ('infraestructura', 'Infraestructura')], max_length=20)),
                ('criticidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('descripcion', models.TextField(blank=True)),
                ('ubicacion', models.CharField(blank=True, max_length=100)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'activos',
            },
        ),
        migrations.CreateModel(
            name='Amenaza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('tipo', models.CharField(choices=[('phishing', 'Phishing'), ('malware', 'Malware'), ('ransomware', 'Ransomware'), ('sql_injection', 'SQL Injection'), ('xss', 'XSS'), ('fuerza_bruta', 'Fuerza Bruta'), ('error_humano', 'Error Humano'), ('robo_equipos', 'Robo de Equipos'), ('acceso_no_autorizado', 'Acceso No Autorizado')], max_length=30)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField(blank=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'amenazas',
            },
        ),
        migrations.CreateModel(
            name='ControlISO27001',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('dominio', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True)),
                ('implementado', models.BooleanField(default=False)),
                ('fecha_implementacion', models.DateField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'controles_iso27001',
            },
        ),
        migrations.CreateModel(
            name='EvaluacionRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inherente', 'Riesgo inherente'), ('residual', 'Riesgo residual')], default='inherente', max_length=20)),
                ('probabilidad', models.PositiveSmallIntegerField(choices=[(1, 'Muy Baja'), (2, 'Baja'), (3, 'Media'), (4, 'Alta'), (5, 'Muy Alta')])),
                ('impacto', models.PositiveSmallIntegerField(choices=[(1, 'Insignificante'), (2, 'Menor'), (3, 'Moderado'), (4, 'Mayor'), (5, 'Crítico')])),
                ('valor_riesgo', models.PositiveSmallIntegerField()),
                ('nivel', models.CharField(choices=[('bajo', 'Bajo (1-5)'), ('medio', 'Medio (6-10)'), ('alto', 'Alto (11-15)'), ('critico', 'Crítico (16-25)')], max_length=20)),
                ('fecha_evaluacion', models.DateField()),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'evaluaciones_riesgo',
            },
        ),
        migrations.CreateModel(
            name='IndicadorCIA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dimension', models.CharField(choices=[('confidencialidad', 'Confidencialidad'), ('integridad', 'Integridad'), ('disponibilidad', 'Disponibilidad')], max_length=20)),
                ('periodo', models.CharField(max_length=7)),
                ('accesos_no_autorizados', models.PositiveIntegerField(default=0)),
                ('incidentes_alteracion', models.PositiveIntegerField(default=0)),
                ('tiempo_indisponibilidad_min', models.PositiveIntegerField(default=0)),
                ('nivel_riesgo_residual', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('percepcion_seguridad', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('registrado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'indicadores_cia',
            },
        ),
        migrations.CreateModel(
            name='Riesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('descripcion', models.TextField()),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'riesgos',
            },
        ),
        migrations.CreateModel(
            name='TratamientoRiesgo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estrategia', models.CharField(choices=[('mitigar', 'Mitigar'), ('transferir', 'Transferir'), ('evitar', 'Evitar'), ('aceptar', 'Aceptar')], max_length=20)),
                ('control_aplicado', models.TextField()),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('riesgo_residual', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'tratamientos_riesgo',
            },
        ),
        migrations.CreateModel(
            name='Vulnerabilidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('nombre', models.CharField(max_length=200)),
                ('descripcion', models.TextField()),
                ('severidad', models.CharField(choices=[('baja', 'Baja'), ('media', 'Media'), ('alta', 'Alta'), ('critica', 'Crítica')], max_length=20)),
                ('estado', models.CharField(choices=[('abierta', 'Abierta'), ('en_tratamiento', 'En tratamiento'), ('mitigada', 'Mitigada'), ('cerrada', 'Cerrada')], default='abierta', max_length=20)),
                ('evidencia', models.FileField(blank=True, null=True, upload_to='riesgos/vulnerabilidades/')),
                ('detectada_en', models.DateField(auto_now_add=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vulnerabilidades',
            },
        ),
    ]
