# Generated by Django 5.2.13 on 2026-06-07 21:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('riesgos', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activo',
            name='propietario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='activos_propiedad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='controliso27001',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles_iso', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='evaluacionriesgo',
            name='evaluado_por',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='indicadorcia',
            unique_together={('dimension', 'periodo')},
        ),
        migrations.AddField(
            model_name='riesgo',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='riesgos', to='riesgos.activo'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='amenaza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='riesgos', to='riesgos.amenaza'),
        ),
        migrations.AddField(
            model_name='evaluacionriesgo',
            name='riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evaluaciones', to='riesgos.riesgo'),
        ),
        migrations.AddField(
            model_name='controliso27001',
            name='riesgo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='controles', to='riesgos.riesgo'),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='evaluacion_residual',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tratamientos', to='riesgos.evaluacionriesgo'),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='responsable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tratamientos_riesgo', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='riesgo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tratamientos', to='riesgos.riesgo'),
        ),
        migrations.AddField(
            model_name='vulnerabilidad',
            name='activo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vulnerabilidades', to='riesgos.activo'),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='vulnerabilidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riesgos', to='riesgos.vulnerabilidad'),
        ),
    ]
