# Generated by Django 5.2.13 on 2026-06-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('riesgos', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evaluacionriesgo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='riesgo',
            name='eliminado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tratamientoriesgo',
            name='activo',
            field=models.BooleanField(default=True),
        ),
    ]
