# Generated by Django 5.2.13 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleInventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_sistema', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cantidad_fisica', models.DecimalField(decimal_places=2, max_digits=12)),
                ('diferencia', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('observaciones', models.TextField(blank=True)),
            ],
            options={
                'db_table': 'detalle_inventario_fisico',
            },
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote', models.CharField(max_length=50)),
                ('cantidad', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('ubicacion', models.CharField(default='Almacén principal', max_length=100)),
                ('clasificacion', models.CharField(blank=True, choices=[('conforme', 'Conforme (>60 días)'), ('reposicion', 'Reposición (30-60 días)'), ('alta_prioridad', 'Alta prioridad (<30 días)'), ('retiro_inmediato', 'Retiro inmediato (caducado)')], max_length=20)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'inventarios',
            },
        ),
        migrations.CreateModel(
            name='InventarioFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('fecha', models.DateField()),
                ('estado', models.CharField(choices=[('en_proceso', 'En proceso'), ('finalizado', 'Finalizado'), ('cancelado', 'Cancelado')], default='en_proceso', max_length=20)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'inventarios_fisicos',
            },
        ),
        migrations.CreateModel(
            name='MovimientoInventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('entrada', 'Entrada'), ('salida', 'Salida'), ('ajuste', 'Ajuste'), ('transferencia', 'Transferencia')], max_length=20)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_anterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('stock_posterior', models.DecimalField(decimal_places=2, max_digits=12)),
                ('referencia', models.CharField(blank=True, max_length=100)),
                ('observaciones', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'movimientos_inventario',
                'ordering': ['-creado_en'],
            },
        ),
    ]
