# Generated by Django 5.2.13 on 2026-06-07 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('inventario', '0001_initial'),
        ('logistica', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventario',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventarios', to='logistica.producto'),
        ),
        migrations.AddField(
            model_name='detalleinventariofisico',
            name='inventario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventario.inventario'),
        ),
    ]
