# Generated by Django 5.2.13 on 2026-06-07 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movimientoinventario',
            name='codigo',
            field=models.CharField(blank=True, max_length=30, unique=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_fecha',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_numero',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_serie',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='doc_tipo',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='motivo',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tercero_documento',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tercero_nombre',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='movimientoinventario',
            name='tercero_tipo',
            field=models.CharField(blank=True, choices=[('proveedor', 'Proveedor'), ('cliente', 'Cliente')], max_length=20),
        ),
    ]
