# Generated by Django 5.2.13 on 2026-06-07 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=30, unique=True)),
                ('titulo', models.CharField(max_length=200)),
                ('tipo', models.CharField(choices=[('interna', 'Interna'), ('externa', 'Externa'), ('seguridad', 'Seguridad de la información'), ('iso27001', 'ISO 27001')], max_length=20)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('alcance', models.TextField()),
                ('hallazgos', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('programada', 'Programada'), ('en_curso', 'En curso'), ('finalizada', 'Finalizada')], default='programada', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'auditorias',
            },
        ),
        migrations.CreateModel(
            name='RegistroAuditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accion', models.CharField(max_length=100)),
                ('modulo', models.CharField(max_length=50)),
                ('tabla', models.CharField(blank=True, max_length=50)),
                ('registro_id', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('datos_anteriores', models.JSONField(blank=True, null=True)),
                ('datos_nuevos', models.JSONField(blank=True, null=True)),
                ('descripcion', models.TextField(blank=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'registros_auditoria',
                'ordering': ['-creado_en'],
            },
        ),
    ]
